### ISSUE TITLE
.json file differences

### ISSUE THREAD

**Issue by cachaito** [IceTimux/one-dark-sublime-text-3-color-scheme#1]
Hi! Great attempt to bring Sublime Text a new color scheme! 

Look at this compare:
![sbl_atm](https://cloud.githubusercontent.com/assets/4311424/8373977/d57d4046-1bf1-11e5-8099-f39534955540.png)

Greetings!

**Comment by IceTimux** [comment]
Hello!
Thanks a lot! I hope you enjoy it! It's made with :heart:

**Comment by IceTimux** [comment]
Hi, thanks! I'll look into this! :+1:

**Comment by IceTimux** [comment]
![screenshot from 2015-06-26 17 42 19](https://cloud.githubusercontent.com/assets/4482351/8387936/c0a6a9bc-1c2a-11e5-80de-e0b1dd8fcf24.png)

Fixed! can you confirm that it works for your needs? thanks :blush:

**Comment by cachaito** [comment]
@IceTimux good job! Looks exactly like Atom 1.0 theme :+1:
