### ISSUE TITLE
single quotes in json files makes text illegible

### ISSUE THREAD

**Issue by pjmp** [IceTimux/one-dark-sublime-text-3-color-scheme#15]
A picture is worth a thousand words so here's one:

![selection_002](https://cloud.githubusercontent.com/assets/11157420/18743791/7852bd98-80da-11e6-8db4-5898b1b14d41.png)

Note: _I know using single quote inside a json file is stupid_

**Comment by sinkingpoint** [comment]
At least according to the state machine [on the JSON website](http://www.json.org/), single quotes are invalid when it comes to strings in a JSON file. So this will be picking up the syntax highlighting for an error.
