### ISSUE TITLE
minor difference with SCSS text color

### ISSUE THREAD

**Issue by cachaito** [IceTimux/one-dark-sublime-text-3-color-scheme#3]
Hi @IceTimux!
This time I've found a minor discrepancy on text color of `touch-action` rule:

![compare](https://cloud.githubusercontent.com/assets/4311424/8407824/c94c99ae-1e6a-11e5-8e66-1c38703edb5b.png)

**Comment by IceTimux** [comment]
Alright thanks, I'll fix this later today :smiley:

**Comment by IceTimux** [comment]
@cachaito what package are you using for .scss syntax highlighting?

**Comment by cachaito** [comment]
This one: [The TextMate SCSS Official Bundle](https://github.com/MarioRicalde/SCSS.tmbundle)

**Comment by IceTimux** [comment]
@cachaito fixed, you can download it straight from github, don't know how long before package control sees the new release :+1:

**Comment by cachaito** [comment]
Good job :ok_hand:
