### ISSUE TITLE
CSS property dark while writing

### ISSUE THREAD

**Issue by vaff** [IceTimux/one-dark-sublime-text-3-color-scheme#4]
The text simply unreadable while typing, and if the proberty is misspelled it stays that way.

![eksempel](https://cloud.githubusercontent.com/assets/351447/8456444/c1e3ce1a-200b-11e5-886c-610e3a264709.png)

**Comment by IceTimux** [comment]
is this in a .scss/sass file? if so, what Sass/Scss syntax highlighting package are you using? this will help me recreate the bug so I can fix it. I'm currently not experiencing it using this highlighter for .scss files.

![screenshot from 2015-07-01 10 17 35](https://cloud.githubusercontent.com/assets/4482351/8456592/6fc81d2e-1fda-11e5-8e54-1d35a51de19b.png)

thanks!

**Comment by vaff** [comment]
Standard scss package. But I have the setting on that highlightes current line.

**Comment by IceTimux** [comment]
where do you set that setting?

**Comment by vaff** [comment]
```
"highlight_line": true,
```

In your user config.

**Comment by IceTimux** [comment]
I've replicated the bug, I'll get to fixing it :+1:

**Comment by ausminternet** [comment]
Any news on this bug?

**Comment by IceTimux** [comment]
sadly I still haven't found a way to solve this problem @ausminternet

**Comment by St3Ko** [comment]
i use [this](https://packagecontrol.io/packages/Sass) highlighting package + highlight current line

no problems here

**Comment by IceTimux** [comment]
@St3Ko Thanks for the comment! I would advise everyone to use that package instead.
