### ISSUE TITLE
Various inconsistencies

### ISSUE THREAD

**Issue by foxx** [IceTimux/one-dark-sublime-text-3-color-scheme#5]
Notice that `self, **kwargs` is the wrong color

## Atom Editor
![screen shot 2015-08-17 at 15 09 44](https://cloud.githubusercontent.com/assets/651797/9306721/0a002634-44f2-11e5-8208-d46ef2936c36.png)

## ST3

![screen shot 2015-08-17 at 15 09 47](https://cloud.githubusercontent.com/assets/651797/9306723/0c6ee036-44f2-11e5-822b-6f4ecf5f8e59.png)

**Comment by foxx** [comment]
Another mismatch, this time with the brackets on class definition;

## Atom

![screen shot 2015-08-17 at 15 10 42](https://cloud.githubusercontent.com/assets/651797/9306783/502b5070-44f2-11e5-972f-f99692f688e4.png)

## ST3

![screen shot 2015-08-17 at 15 10 45](https://cloud.githubusercontent.com/assets/651797/9306785/55959e3a-44f2-11e5-8cf3-17c309f1ae53.png)

**Comment by foxx** [comment]
And another, kwargs/bool colouring not consistent.

## Atom

![screen shot 2015-08-17 at 15 12 32](https://cloud.githubusercontent.com/assets/651797/9306801/72ac1bac-44f2-11e5-81d0-0db916e16dec.png)

## ST3

![screen shot 2015-08-17 at 15 12 26](https://cloud.githubusercontent.com/assets/651797/9306804/75847d74-44f2-11e5-8b3b-400353d00187.png)

**Comment by foxx** [comment]
And another, this time it's missing `XXX/TODO` highlighting;

## Atom

![screen shot 2015-08-17 at 15 36 51](https://cloud.githubusercontent.com/assets/651797/9307324/e98fc7ac-44f5-11e5-80c6-cc2045a3b522.png)

## ST3

![screen shot 2015-08-17 at 15 37 38](https://cloud.githubusercontent.com/assets/651797/9307325/ec407924-44f5-11e5-8bfc-338cec4fa03f.png)

**Comment by IceTimux** [comment]
thank's for sending these in, they will be fixed within the coming weeks

**Comment by IceTimux** [comment]
Hey @foxx sorry i took a long time, I went ahead and was able to fix all but the last of the inconsistencies you've reported. Thanks a lot for your help. If you have more please send them in. I will be trying to fix the commet XXX one too soon.

**Comment by foxx** [comment]
Nice work, thanks!

**Comment by IceTimux** [comment]
no problem!
