### ISSUE TITLE
Python super and self keywords not being highlighted

### ISSUE THREAD

**Issue by danielgoncalves** [IceTimux/one-dark-sublime-text-3-color-scheme#6]
I'm using One Dark color scheme along with One Dark Material [1] theme.
I'm not sure if this is an issue in the color scheme or not. Anyways, I think it's worth to note.

![g4797](https://cloud.githubusercontent.com/assets/737884/11632718/59a91ed4-9cef-11e5-9bee-1d3ba09f57fb.png)

[1] https://packagecontrol.io/packages/One%20Dark%20Material%20-%20Theme

**Comment by IceTimux** [comment]
This is a problem with the "One Dark Material - Theme" package. What's happening is the developer of that theme is not using the latest version of my syntax theme. 

You can solve the issue by asking the developer of the "One Dark Material - Theme" to update and use the latest version of my syntax theme. Or not use the "One Dark Material - Theme" package but instead use "One Dark Color Scheme" package (https://packagecontrol.io/packages/One%20Dark%20Color%20Scheme)
