### ISSUE TITLE
LaTeX labels not colored

### ISSUE THREAD

**Issue by ghlecl** [IceTimux/one-dark-sublime-text-3-color-scheme#7]
Working on some LaTeX documents and noticed that the labels (set with the `\label{ the_name }` command) are not coloured in the theme whereas they are in Atom.  I have taken snapshots.  Will check if I find any other discrepancies.  Thanks for the theme.

<img width="842" alt="atom" src="https://cloud.githubusercontent.com/assets/8061814/11648155/d8ea1bc2-9d3e-11e5-841a-87b1036132b5.png">
<img width="874" alt="sublime" src="https://cloud.githubusercontent.com/assets/8061814/11648156/dbac03e8-9d3e-11e5-8846-13024d2fae68.png">

**Comment by ghlecl** [comment]
Should probably have waited to write more things in just one post.  Anyhow, just realized that the contents of an emphasized piece of text `\emph{some text}` is italicized in Atom whereas it is not in Sublime.  Again, snapshots to show

Atom

<img width="864" alt="atom" src="https://cloud.githubusercontent.com/assets/8061814/11648209/70051854-9d3f-11e5-9860-85155910b997.png">


Sublime

<img width="834" alt="sublime" src="https://cloud.githubusercontent.com/assets/8061814/11648212/73863260-9d3f-11e5-9dac-8e11f20499cd.png">

**Comment by IceTimux** [comment]
awesome, thanks for sending these in.

**Comment by IceTimux** [comment]
Just pushed the update buddy, thanks again.
